### ISSUE TITLE
“libpng error: Call to NULL write function” on writing image

### ISSUE THREAD

**Issue by vladtepesch** [benkasminbullock/image-png-libpng#23]
asked first here -> https://stackoverflow.com/questions/44566732/imagepnglibpng-libpng-error-call-to-null-write-function

I have some code that should modify the tEXt or zTXt chunk of a PNG file with the Perl bindings of the libpng.

Code:

    use strict;
    use warnings;
    use Data::Dumper qw(Dumper);
    use Image::PNG::Libpng qw(read_png_file write_png_file) ;
    
    
    my $lpng = read_png_file ("testimg.png");
    
    my @cmdAr = ();
    for(my $i=0; $i<10; ++$i){
      push(@cmdAr, {compression => Image::PNG::Libpng::PNG_TEXT_COMPRESSION_zTXt ,
                    key => sprintf("par_%02i",$i),
                    text => sprintf("%06i", $i*$i)
                   }
          );
    }
    print STDERR Dumper(\@cmdAr);
    $lpng->set_text (\@cmdAr);
    $lpng->write_png_file ("testimg2.png");

but the code fails at the write function with:

> libpng error: Call to NULL write function

Any hints about how to fix this? The files exists and the process also has write access.

My Perl version (latest Strawberry Perl):

> This is perl 5, version 26, subversion 0 (v5.26.0) built for
> MSWin32-x86-multi-thread-64int

Version of the libpng module:

> cpan -D Image::PNG::Libpng

    CPAN: CPAN::SQLite loaded ok (v0.211)
    Database was generated on Thu, 15 Jun 2017 10:43:51 GMT
    
    Image::PNG::Libpng
    -------------------------------------------------------------------------
    	CPAN: Module::CoreList loaded ok (v5.20170530)
    (no description)
    	B/BK/BKB/Image-PNG-Libpng-0.43.tar.gz
    	C:\strawberry-perl\perl\site\lib\Image\PNG\Libpng.pm
    	Installed: 0.43
    	CPAN:      0.43  up to date
    	Ben Bullock (BKB)
    	bkb@cpan.org

**Comment by benkasminbullock** [comment]
Thank you for the bug report.

The reason this does not work is explained in the module documentation at
the following link.

https://metacpan.org/pod/Image::PNG::Libpng#write_png_file

Please let me know if you have any further problems with the module.

**Comment by vladtepesch** [comment]
oh sorry for filing this as an issue - i overlooked this.
Maybe add an example section for read modify write action.

I now added 

     my $lpng = $lpng->copy_png();

Anything wrong with this solution?

**Comment by benkasminbullock** [comment]
> oh sorry for filing this as an issue - i overlooked this.

It's not a problem.

> Anything wrong with this solution?

No, that should work.

You are right that there is currently no example with copy_png. I'll consider adding an example with copy_png.

**Comment by vladtepesch** [comment]
okay, thank you. may be the `set_text` (and possibly some other set_xxx-functions) should fail, if there is no write-structure. Currently calling the above copy-line after the `set_text` does not fail but the chunks are not present in the output.

**Comment by benkasminbullock** [comment]
You are overwriting the variable with a new value.
