### ISSUE TITLE
Add support for `png_set_compression_level`, to enable output of uncompressed PNG images

### ISSUE THREAD

**Issue by nandhp** [benkasminbullock/image-png-libpng#24]
In some circumstances (e.g. generating 30 video frames per second) it is useful to maximize encoding speed by outputting uncompressed PNGs. This is accomplished using the [libpng function `png_set_compression_level`](http://www.libpng.org/pub/png/libpng-1.2.5-manual.html#section-4.2). Please consider adding support for this function.

**Comment by benkasminbullock** [comment]
I have incorporated this change into the following:

https://metacpan.org/release/BKB/Image-PNG-Libpng-0.44_01

Now you must (must) download and test that. You should also provide a test
script that shows that it does what you want.

**Comment by benkasminbullock** [comment]
No response so I'm deleting these changes.
