### ISSUE TITLE
Ready for Prime Time?

### ISSUE THREAD

**Issue by PhilterPaper** [benkasminbullock/image-png-libpng#26]
I am supporting PDF::Builder (on GitHub and CPAN), which includes a pure Perl library for PNG image support (just reading, I think). It was originally on PDF::API2 (Builder is a fork), so if you have any familiarity with that product, that's a head start. There is a reported bug where RGBA support is hundreds of times slower than RGB image processing, so I am interested in finding a library that would foist most of the nitty gritty of PNG processing off on to someone else. Naturally, it would have to be reasonably complete (at least as complete as the current library, which isn't saying a whole lot), reasonably clean and fast, and **supported**. What is the state of Image::PNG::Libpng? I see that it has been stuck at release 0.45 for a while, which concerns me.

There's no guarantee that I'll be able to use it, as I will need to understand and remap PDF::Builder's entire PNG processing code into calls to the new libpng-using interface. I think the problem in the current pure Perl library is literally millions of calls to Perl's **vec()** call (only when handling RBGA), which may not be too fast. 

By the way, how do you connect CPAN "Issues" to GitHub? My support is on GitHub, too so it would be nice to redirect CPAN to GitHub.

**Comment by benkasminbullock** [comment]
Are you thinking about replacing this code with Image::PNG::Libpng?

https://metacpan.org/source/PMPERRY/PDF-Builder-3.010/lib/PDF/Builder/Resource/XObject/Image/PNG.pm

It will probably be faster than that. I'm not sure what you need to do with the data once it's read in though. The gain for you would be not using the Perl unprocess routine in that.

**Comment by PhilterPaper** [comment]
Yes, that's the module. Here's what it supposedly supports:

options: -notrans
   No transparency -- ignore tRNS chunk if provided, ignore Alpha channel if provided.

**Supported PNG types**

- (0) Gray scale of depth 1, 2, 4, or 8 bits per pixel (2, 4, 16, or 256 gray levels). 16 bps is not currently supported. Transparency via the tRNS chunk is allowed, unless the -notrans option is given.
- (2) RGB 24-bit truecolor with 8 bits per sample (16.7 million colors). 16 bps is not currently supported. Transparency via the tRNS chunk is allowed, unless the -notrans option is given.
- (3) Palette color with 1, 2, 4, or 8 bits per pixel depth (2, 4, 16, or 256 color table entries). 16 bpp is not currently supported. Transparency via the tRNS chunk is allowed, unless the -notrans option is given.
- (4) Gray scale of depth 8 bits per pixel plus 8 bit Alpha channel (256 gray levels and 256 levels of transparency). 16 bpp is not currently supported. The Alpha channel is ignored if the -notrans option is     given. The tRNS chunk is not permitted.
- (6) RGB 24-bit truecolor with 8 bits per sample (16.7 million colors) plus 8 bit Alpha channel (256 levels of transparency). 16 bps is not currently supported. The Alpha channel is ignored if the -notrans        option is given. The tRNS chunk is not permitted.

Being able to support the currently unsupported bit depths would be a bonus (provided PDF can handle them!). The library should support in some manner ignoring transparency (Alpha channel or tRNS chunk) -- if I need to modify the data after it's been read in, as long as that's documented somewhere _and overall it's faster than the current library_, it's OK. This is for PDF output, and I don't think it can do any operations on combining images, so ignoring transparency may not be important. I don't know exactly what the final output is supposed to be that is turned over to other routines -- I guess I'll have to experiment a bit!

Anyway, if you think your library can support these requirements, I'll give it a try. Worst case, it doesn't, and I have to fall back to the current library. I can implement it so both are in use (if yours is installed), preferably using yours unless it encounters something it can't handle. Thanks much!

**Comment by benkasminbullock** [comment]
I think it should be able to do all the things you want. It's meant to be basically a Perl-ized libpng, and almost everything in libpng which seemed to be useful is supported. Let me know how it goes and if you get stuck I'll try to help.

**Comment by PhilterPaper** [comment]
Well, I tried the first step of installing Image::PNG::Libpng on my Windows 10 + Strawberry Perl 5.26, via the "cpan" "install Image::PNG::Libpng" command, and it failed. The first message is that Makefile.PL can't compile the source because "'cc' is not recognized as an internal or external command, operable program or batch file." Strawberry has a C compiler on it (named "gcc") that I can install other packages with -- have you tested on Strawberry? It then goes on to say that libpng is not installed -- it is (C:\strawberry\c\lib\libpng.a). My PDF::Builder package does not send C source, so I can't help with how to build the package. Thoughts?

**Comment by benkasminbullock** [comment]
Thanks for the input.

As you correctly said, the use of `cc` to compile the program is a bug. This is in the file `inc/CheckForLibPng.pm`, it should be using `$Config{cc}` to get the same compiler as used to build Perl itself. I'm not sure about the other things. I have not installed this on Strawberry Perl and did not know that it featured libpng. There should be a way to compile it for that system, but it seems to need some special include path headers.

I also found that inc/CheckForLibPng.pm had not been put under version control at all, due to previous use of the inc directory for Devel::CheckLib, so this commit looks a bit strange:

commit 12ca2cbbe5fd4fb9aee7b6bc4743fa96123eab92 (HEAD -> master, origin/master)
Author: Ben Bullock <benkasminbullock@gmail.com>
Date:   Fri Sep 14 11:54:10 2018 +0900

    Put CheckForLibPng.pm under version control; bug with cc
    
    This script had been developed extensively but never put under version control due to an error in .gitignore where inc/* was ignored. That dated from the time I was using Devel::CheckLib to build this system.
    
    Also, this fixes a bug where CheckForLibPng was using cc not
    $Config{cc} for the compiler.

**Comment by benkasminbullock** [comment]
OK there was an error in the last commit, fixed here:

commit 9e54c8e6c1c5e9a3225b6fdfe2c8f4ea1f686392 (HEAD -> master, origin/master)
Author: Ben Bullock <benkasminbullock@gmail.com>
Date:   Fri Sep 14 12:06:52 2018 +0900

    Use the $cc variable not cc; die if no $cc found

Now I edit inc/CheckForLibPng.pm to the following lines:
<pre>
my $png_lib_dir = 'C:/Strawberry/c/lib/';
my $png_include_dir = 'C:/Strawberry/c/include/libpng';
</pre>
and it installed correctly and also did `make test` OK:
<pre>
C:\Users\ben\Documents\Image-PNG-Libpng-0.45>gmake test
"C:\Strawberry\perl\bin\perl.exe" -MExtUtils::Command::MM -e cp_nonempty -- Libpng.bs blib\arch\auto\Image\PNG\Libpng\Libpng.bs 644
"C:\Strawberry\perl\bin\perl.exe" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib\lib', 'blib\arch')" t/*.t
t/bKGD.t ........... ok
t/bogus.t .......... skipped: libpng version is 1.6.29
t/cHRM.t ........... ok
t/Const.t .......... ok
t/copy-all-png.t ... ok
t/functions.t ...... ok
t/gAMA.t ........... ok
t/get-internals.t .. ok
t/get-text.t ....... ok
t/hIST.t ........... ok
t/Libpng.t ......... ok
t/pHYs.t ........... ok
t/PLTE.t ........... ok
t/sBIT.t ........... ok
t/sCAL.t ........... ok
t/set-text.t ....... ok
t/sPLT.t ........... ok
t/supports.t ....... ok
t/tIME.t ........... ok
t/tRNS.t ........... ok
t/user-limits.t .... ok
All tests successful.
Files=21, Tests=274,  3 wallclock secs ( 0.06 usr +  0.00 sys =  0.06 CPU)
Result: PASS

C:\Users\ben\Documents\Image-PNG-Libpng-0.45>
</pre>
The only thing left to do is to make it detect the strawberry perl lib locations automatically, then it should be OK.

**Comment by benkasminbullock** [comment]
After a bit of work, it seems that nothing more needs to be done to make it find any Strawberry Perl libraries, they seem to be found without any further effort. I've released a provisional testing version to CPAN, if you're still interested in using the module please download from the following link and try installing that.

https://cpan.metacpan.org/authors/id/B/BK/BKB/Image-PNG-Libpng-0.45_01.tar.gz

It works on my Strawberry Perl.

**Comment by benkasminbullock** [comment]
The first CPAN testers result on Windows has come through:

http://www.cpantesters.org/cpan/report/a7add179-6bf3-1014-b801-4147b78b2be9

Looks like it is working on Strawberry Perl now.  It had never built on Windows before:

http://matrix.cpantesters.org/?dist=Image-PNG-Libpng%200.45

Even if nothing else comes from this discussion, I think that was a good result.

**Comment by PhilterPaper** [comment]
Well, I've got _something_ installed now. D/L the .tar.gz file onto my desktop, unpack it via 7-zip, cd to the dir and run perl Makefile.PL, gmake test, and gmake install. "cpan" claims that Image::PNG::Libpng 0.45_01 now exists. I see a new file Libpng.pm in the Strawberry lib/Image/PNG/ directory, as well as Const.pm, Libpng.pod, and memory-test.pl -- is anything else expected?

Time to start playing with this thing. I'll let you know how it turns out. Thanks much for the quick fix.

**Comment by PhilterPaper** [comment]
I've been working through it, comparing the Libpng interface to the old (pure Perl) code. It's messy, but I think if I just work very carefully through it, I can get it to function properly. It looks like the new (Libpng) functionality will be a superset of the old, which is an improvement.

I do have a few questions:
When unpacking the header (IHDR), the old code produces flags for the compression method, the

**Comment by PhilterPaper** [comment]
Why do they put the Close button right next to the Comment button....? Post above continued...

**Comment by benkasminbullock** [comment]
> 
> 
> I've been working through it, comparing the Libpng interface to the old (pure Perl) code. It's messy, but I think if I just work very carefully through it, I can get it to function properly. It looks like the new (Libpng) functionality will be a superset of the old, which is an improvement.
> 
> I do have a few questions. When unpacking the header (IHDR), the old code produces flags for the compression method, the filter method, and the interlace method. All must be 0.
> 

The interlace method can be one of two values, but the compression method and the filter method are always zero within libpng itself, they were intended as expansions but were never implemented. You can try the libpng mailing list if you want more details.

>     1. What is the compression method, and has that been dealt with already (i.e., I can ignore it)?

Yes, the compression is always done by zlib and you don't need to decompress if you are using libpng. That is done by the library.
 
>     2. What is the filter method, and do I need to do anything with it at the point I receive the data?

See above.

>     3. I see the interlace method comes back with the IHDR: what is the difference between NONE and ADAM7? Is ADAM7 simple scan line interlacing like on a TV (rows 0,2,4,... last-even, 1,3,5,... last-odd), or something else? Has it already been de-interlaced (all rows in order, = progressive scan)? The PDF spec doesn't say anything about interlacing, so I'm assuming it must be non-interlaced at the point I hand it over to the common image support routines.

I'm not exactly sure of the details of ADAM7. As mentioned above you could try the libpng mailing list or the document of the PNG format, but you don't need to worry about that since the image data is decompressed and sorted into pixels by libpng. Interlacing like that was used in the 1990s for very slow internet connections, it's not very important now, but the library does it all automatically anyway.

Coincidentally, some info here:

http://libpng.org/pub/png/pngpics.html

I wouldn't bother unless you are interested for its own sake though.

There are some tests of it all in the module somewhere I believe. It incorporates all of the libpng test images in directory t/libpng/.

**Comment by PhilterPaper** [comment]
OK, I'll give some interlaced (ADAM7) images a try. PDF doesn't seem to do interlaced, but if the flag is just for historical interest and the data has already been de-interlaced, it might work. If not, is there a flag to explicitly de-interlace (if the file is interlaced) that I overlooked? If compression method and filter method were never implemented, I'll just leave a note in the code that they should be 0 (any point in checking?) and they're ignored. So, by the time I receive the image data, it should be in a standardized form with all compression and filtering removed? That would be good if I don't have to handle that in Perl code.

When I request that the Alpha channel be stripped, does that turn a color type 6 into a type 2, or does it still come back as type 6? I'm assuming that stripping the Alpha channel turns a translucent image fully opaque. Likewise, I'm assuming that simply ignoring the tRNS chunk will result in a fully opaque image. Am I misreading either of these? I haven't tried them out yet.

Finally, I need to find some sample images to test in PDF; I hope the ones you supply in t/libpng/ will do the job. I will need gray, gray+alpha, rgb, rgb+alpha, palette, gray+tRNS, rgb+tRNS, and palette+tRNS; all in a variety of bit depths if I want to do a thorough job of testing.

**Comment by benkasminbullock** [comment]
On Mon, 17 Sep 2018 at 22:00, Phil Perry <notifications@github.com> wrote:

> OK, I'll give some interlaced (ADAM7) images a try. PDF doesn't seem to do
> interlaced, but if the flag is just for historical interest and the data
> has already been de-interlaced, it might work. If not, is there a flag to
> explicitly de-interlace (if the file is interlaced) that I overlooked? If
> compression method and filter method were never implemented, I'll just
> leave a note in the code that they should be 0 (any point in checking?) and
> they're ignored. So, by the time I receive the image data, it should be in
> a standardized form with all compression and filtering removed? That would
> be good if I don't have to handle that in Perl code.
>

You don't need to even think about interlacing. The pixels are put into the
x and y coordinates of the image and de-interlaced by the library. When you
write the image, you put the interlacing as you want, and the library
handles it. When you read the image, the library puts all the pixels back
into where they are supposed to be in your original image, and the
interlacing key is only for information. This is completely handled by
libpng, there is nothing for you to do.



> When I request that the Alpha channel be stripped, does that turn a color
> type 6 into a type 2, or does it still come back as type 6? I'm assuming
> that stripping the Alpha channel turns a translucent image fully opaque.
> Likewise, I'm assuming that simply ignoring the tRNS chunk will result in a
> fully opaque image. Am I misreading either of these? I haven't tried them
> out yet.
>

tRNS is for paletted images, so you have pixels containing one byte and
each byte corresponds to a particular RGB point in the palette. If there is
a tRNS then that byte also has an alpha associated with it.


> Finally, I need to find some sample images to test in PDF; I hope the ones
> you supply in t/libpng/ will do the job. I will need gray, gray+alpha, rgb,
> rgb+alpha, palette, gray+tRNS, rgb+tRNS, and palette+tRNS; all in a variety
> of bit depths if I want to do a thorough job of testing.
>
> http://www.libpng.org/pub/png/pngsuite.html

>

**Comment by PhilterPaper** [comment]
OK, good news on interlacing (i.e., I can ignore it).

I think you misread my question about transparency. Two separate issues: does simply stripping Alpha (parameter to the read function) do the job to make the image opaque (for gray+Alpha, RGB+Alpha), and is the result with the original color type (6 stays 6, and does not become 2)? Second issue: my understanding is that gray and RGB, as well as palette, can have a tRNS transparency chunk. If I want opaque images, I would just ignore any tRNS chunk?

**Comment by benkasminbullock** [comment]
On Tue, 18 Sep 2018 at 07:58, Phil Perry <notifications@github.com> wrote:

> OK, good news on interlacing (i.e., I can ignore it).
>

Yes, you can ignore compression and interlacing and filtering.


> I think you misread my question about transparency. Two separate issues:
> does simply stripping Alpha (parameter to the read function) do the job to
> make the image opaque (for gray+Alpha, RGB+Alpha), and is the result with
> the original color type (6 stays 6, and does not become 2)? Second issue:
> my understanding is that gray and RGB, as well as palette, can have a tRNS
> transparency chunk. If I want opaque images, I would just ignore any tRNS
> chunk?
>

I'm not sure of the answers to these questions. I haven't used the
image-altering functions very much except for the BGRA/RGBA function,
because I mostly use RGBA images, so I suggest you experiment with it or
ask on the libpng mailing list. My Perl module just implements libpng's
functions in Perl, so you're literally calling the C functions of libpng,
so whatever that does is what my module does.

**Comment by benkasminbullock** [comment]
I've asked you above to ask your questions about what's provided by libpng on the libpng mailing list. I apologise for repeating myself, but if you do have questions about what libpng provides, can you please ask the libpng people about that? Thank you.
