### ISSUE TITLE
Compression level?

### ISSUE THREAD

**Issue by greg-kennedy** [benkasminbullock/image-png-libpng#32]
Is it possible to set compression level of PNG images using this library?  I checked the .xs and it appears that the relevant function is wrapped in `#if (0)`... what's the reason for that?

```xs
void
perl_png_set_compression_level (Png, level)
	Image::PNG::Libpng Png;
	int level
CODE:
	png_set_compression_level (Png->png, level);
```

**Comment by greg-kennedy** [comment]
reference #24

**Comment by benkasminbullock** [comment]
The reason is the person I did that change for didn't respond. The best I can offer you is to uncomment that block:

https://metacpan.org/release/BKB/Image-PNG-Libpng-0.48_01

Please, download, confirm.

**Comment by greg-kennedy** [comment]
It's working for me.  Here is a test file you can dump into `t/compress_level.t` that uses the PngSuite example zlib files.  This might be fragile since it might depend on your zlib version.
```perl
use warnings;
use strict;
use Test::More;
use FindBin '$Bin';
use Image::PNG::Libpng ':all';
use Data::Dumper;

# these are mappings in the PngSuite of filename to compression level used
my %levels = (
  z00n2c08 => 0,
  z03n2c08 => 1,
  z06n2c08 => 2,
  z09n2c08 => 9
);

# read the example file
foreach my $file (keys %levels) {
    my $ffile = sprintf("%02s/libpng/%s.png", $Bin, $file);
    my $src_size = -s $ffile;
    my $src_png = read_png_file ($ffile);
    ok ($src_png);

    my $src_level = $levels{$file};
    foreach my $target_level (values %levels) {
      next if $src_level == $target_level;
      my $dest_png = copy_png($src_png);
      $dest_png->set_compression_level($target_level);
      my $output = $dest_png->write_to_scalar();
      my $dest_size = length $output;
      if ($src_level < $target_level) {
        ok( $src_size >= $dest_size,
          "source $file (level: $src_level, $src_size bytes) larger than target (level: $target_level, $dest_size bytes)" );
      } else {
        ok( $src_size <= $dest_size,
          "source $file (level: $src_level, $src_size bytes) smaller than target (level: $target_level, $dest_size bytes)" );
      }
    }
}
done_testing ();
```

**Comment by greg-kennedy** [comment]
maybe want a final check that the filesizes were changed at least once across all tests, to verify that the compression level change actually does *something* heh

**Comment by greg-kennedy** [comment]
oh also you probably want to leave this one defined out

```xs
void
perl_png_set_crc_action  (Png, crit_action, ancil_action);
	Image::PNG::Libpng Png;
	int crit_action;
	int ancil_action;
CODE:
	png_set_crc_action (Png->png, crit_action, ancil_action);
```

this is something else having to do with validation that should probably be more Perl-ish than whatever the lib is doing already
> If you use libpng then you call png_set_crc_action() to tell it what to do on validation failure. The actions are "warn, and use the data", "warn and discard the data", "use the data without warning", "warn and discard the data" (for non-critical chunks), and "exit with an error." All reasonable actions for different circumstances.

**Comment by benkasminbullock** [comment]
On Mon, 7 Dec 2020 at 14:06, Greg Kennedy <notifications@github.com> wrote:

> oh also you probably want to leave this one defined out
>
> voidperl_png_set_crc_action  (Png, crit_action, ancil_action);
> 	Image::PNG::Libpng Png;
> 	int crit_action;
> 	int ancil_action;
> CODE:
> 	png_set_crc_action (Png->png, crit_action, ancil_action);
>
>
I've commented that out.

**Comment by benkasminbullock** [comment]
On Mon, 7 Dec 2020 at 13:50, Greg Kennedy <notifications@github.com> wrote:

> It's working for me. Here is a test file you can dump into
> t/compress_level.t that uses the PngSuite example zlib files. This might
> be fragile since it might depend on your zlib version.
>
zlib has been around since dinosaurs roamed the earth, so there might be
some brontosauruses or pterodactyls using some kind of old zlib version
with different levels but I doubt anyone using recent versions of Perl will
have that problem.

Anyway these XS modules have to be sent through CPAN testers with testing
version numbers before releasing a normal version, so we'll send it through
that and see what happens.

https://metacpan.org/release/BKB/Image-PNG-Libpng-0.48_02

The tests you suggested are in t/kennedy.t, I'll probably change the name
of the file in the release version though.



>

**Comment by greg-kennedy** [comment]
Sorry to nitpick but the test you used for `kennedy.t` is a bit outdated, I edited my comment above a couple times and you may have gotten the old one in email.  Here's the final version I suggest:

```perl
use warnings;
use strict;
use Test::More;
use FindBin '$Bin';
use Image::PNG::Libpng ':all';
use Data::Dumper;

# these are levels in the PngSuite of filename and compression level used
my @levels = ( 0, 3, 6, 9 );

my $filesizes_changed = 0;

# read the example file
foreach my $src_level (@levels) {
    my $ffile = sprintf("%s/libpng/z%02dn2c08.png", $Bin, $src_level);
    my $src_size = -s $ffile;
    my $src_png = read_png_file ($ffile);
    ok ($src_png);

    foreach my $target_level (@levels) {
      my $dest_png = copy_png($src_png);
      $dest_png->set_compression_level($target_level);
      my $output = $dest_png->write_to_scalar();
      my $dest_size = length $output;
      if ($src_level == $target_level) {
        ok( $src_size == $dest_size,
          "source $ffile (level: $src_level, $src_size bytes) equal to target (level: $target_level, $dest_size bytes)" );
      } elsif ($src_level < $target_level) {
        ok( $src_size >= $dest_size,
          "source $ffile (level: $src_level, $src_size bytes) larger than target (level: $target_level, $dest_size bytes)" );
        $filesizes_changed ++;
      } else {
        ok( $src_size <= $dest_size,
          "source $ffile (level: $src_level, $src_size bytes) smaller than target (level: $target_level, $dest_size bytes)" );
        $filesizes_changed ++;
      }
    }
}

ok($filesizes_changed > 0, "At least one file changed size because of compress_level");
done_testing ();
```

**Comment by benkasminbullock** [comment]
I only read the email, I don't really look at the github issue page.

The new changes are here:

https://metacpan.org/release/BKB/Image-PNG-Libpng-0.48_03

You don't seem to actually be using the Data::Dumper dependency so I
removed that.

**Comment by greg-kennedy** [comment]
Looks good to me (and CPANTesters is happy, except the one Windows box that apparently doesn't have libjpeg installed)

**Comment by benkasminbullock** [comment]
I think it's good, I found another issue about text chunks so I'm just running tests on that now:

https://metacpan.org/release/BKB/Image-PNG-Libpng-0.48_05

If the text chunk stuff is OK I will release that version later today or tomorrow as 0.49.

I'll close this now but just reopen if you are not satisfied.

**Comment by benkasminbullock** [comment]
There is some sort of problem with older versions of libpng on Linux so I'm going to reopen this and then close it once things have resolved.

**Comment by benkasminbullock** [comment]
> Looks good to me (and CPANTesters is happy, except the one Windows box that apparently doesn't have libjpeg installed)

The problem with that Windows is actually that it uses libpng 1.6.3 and that version seems to have some issue with iTXt (international text, Unicode text) chunks where it returns the wrong value for the compression. What I did was to skip the tests for that particular libpng version:

https://github.com/benkasminbullock/image-png-libpng/commit/1595db0817463a454dbed07f34a2e6a7c6731410#diff-89cbf2ed85b2ff7e3703a07e592a43dab281b48bb0ca148121edcef46e1d640e

If this passes cpan testers I will release the whole thing as version 0.49.

**Comment by benkasminbullock** [comment]
Thankfully this saga seems to be over:

http://www.cpantesters.org/cpan/report/e0ecdb88-6c09-1014-a3c8-d19ef29aa079

Thanks for the bug report and tests, Greg. Let me know if you notice anything else with the module.

**Comment by greg-kennedy** [comment]
Thank you!
