### ISSUE TITLE
Change/Simplify "png_compare" function

### ISSUE THREAD

**Issue by Baseband-processor** [benkasminbullock/image-png-libpng#33]
Hi, interesting this function, but I think that instead of confront row, it would be better to use the crc from:
```
png_calculate_crc(png_structrp png_ptr, png_const_bytep ptr, size_t length)
{
   int need_crc = 1;

   if (PNG_CHUNK_ANCILLARY(png_ptr->chunk_name) != 0)
   {
      if ((png_ptr->flags & PNG_FLAG_CRC_ANCILLARY_MASK) ==
          (PNG_FLAG_CRC_ANCILLARY_USE | PNG_FLAG_CRC_ANCILLARY_NOWARN))
         need_crc = 0;
   }

   else /* critical */
   {
      if ((png_ptr->flags & PNG_FLAG_CRC_CRITICAL_IGNORE) != 0)
         need_crc = 0;
   }

   /* 'uLong' is defined in zlib.h as unsigned long; this means that on some
    * systems it is a 64-bit value.  crc32, however, returns 32 bits so the
    * following cast is safe.  'uInt' may be no more than 16 bits, so it is
    * necessary to perform a loop here.
    */
   if (need_crc != 0 && length > 0)
   {
      uLong crc = png_ptr->crc; /* Should never issue a warning */

      do
      {
         uInt safe_length = (uInt)length;
#ifndef __COVERITY__
         if (safe_length == 0)
            safe_length = (uInt)-1; /* evil, but safe */
#endif

         crc = crc32(crc, ptr, safe_length);

         /* The following should never issue compiler warnings; if they do the
          * target system has characteristics that will probably violate other
          * assumptions within the libpng code.
          */
         ptr += safe_length;
         length -= safe_length;
      }
      while (length > 0);

      /* And the following is always safe because the crc is only 32 bits. */
      png_ptr->crc = (png_uint_32)crc;
   }
}
```
I am working for a pure perl crc model for image, it would be something similar to:

```
perl
sub png_compare($file1, $file2){
  if( crc($file1) eq crc( $file2){
   return 1;
  }
}
```
I don't know if your library has something for converting 2 file in its binary form and, using your Text::Fuzzy library, could in a first moment find the hamming distance between the 2 files and after, try to understand higher level differences.

(I am working on this, I am really interested in your library for an article about steganalysis.. in the next days I'll add more info).

Regards
Edoardo Mantovani, 2020
```

**Comment by benkasminbullock** [comment]
This doesn't really make sense. The whole point of png_compare is to compare the pixels. If you compare the crc it might save some time rejecting unlike images but if the crc was the same you would still have to compare the pixels.

**Comment by Baseband-processor** [comment]
ok, thanks now I've understood, please verify if I have committed code in "example" and "test"

**Comment by Baseband-processor** [comment]
Sorry one moment, the purpose of "png_compare consists" on compare 2 images and return 0 or 1 if images are the same, an hashing function (maybe not the crc) ideally would be faster and return (probably) the same result.

Regards
Edoardo Mantovani, 2020

**Comment by benkasminbullock** [comment]
Yes "probably" the same result. png_compare started off as a function for testing the module itself, but that ended up being image_data_diff because I wanted more detail.

You seem to be looking for similar image searching, maybe something like this:

https://metacpan.org/release/Image-Similar

might be more useful. There is more information about other Perl libraries here:

https://metacpan.org/pod/Image::Similar#SEE-ALSO

Good luck finding something.

**Comment by benkasminbullock** [comment]
There is also this: https://github.com/runarbu/PerlImageHash

It is Image::Hash on CPAN.

https://metacpan.org/pod/Image::Hash

It seems to be defunct though.
