### ISSUE TITLE
Something broke in 0.53?

### ISSUE THREAD

**Issue by PhilterPaper** [benkasminbullock/image-png-libpng#34]
After all your recent updates to Image::PNG::Libpng, I thought it would be a good idea to test my PDF::Builder PNG test code and make sure it was still working. It wasn't.

At 0.54, it got through the first test's creation of a PNG-based image object, but then apparently blew up Perl when it tried to create an output image in the PDF. No messages of any kind, just an abrupt end to the program (and no output PDF saved). This was with my code unchanged since your 0.47 release.

I force-installed 0.53, and had the same results. I force-installed 0.52 and this time it worked, producing the same visual results as with 0.47, but the stream data appears to be slightly different.

Anyway, could you please review your changes (at least, post-0.52) and see what's changed? If you can't find anything, I can bundle up a test case for you. While I'm waiting, do you want me to see if I can find which version of your library started producing a different decoded stream?

**Comment by benkasminbullock** [comment]
I have changed the code for split_alpha quite extensively.

I checked it against the existing tests which are in

basi4a08-alpha.bin basi4a08-data.bin

in the directory

t/split-alpha

in the distribution. These are all passing all the tests at CPAN testers as
well.

Without information about what isn't working now it's going to be a
guessing game for me, so the best thing is if you can give me at least one
PNG file which doesn't work any more.

**Comment by benkasminbullock** [comment]
Hold on, I found the old files you send before and identified a problem. The 4 and 8 bit depth images seem to be working and the 16 bit ones are failing.
````
/home/ben/projects/image-png-libpng/t/libpng/basn4a16.png
not ok 9 - basn4a16-split-alpha-data.new and basn4a16-data.bin same
#   Failed test 'basn4a16-split-alpha-data.new and basn4a16-data.bin same'
#   at ./ipl.pl line 42.
ok 10 - basn4a16-split-alpha-alpha.new and basn4a16-alpha.bin same
/home/ben/projects/image-png-libpng/t/libpng/basi4a16.png
not ok 11 - basi4a16-split-alpha-data.new and basi4a16-data.bin same
#   Failed test 'basi4a16-split-alpha-data.new and basi4a16-data.bin same'
#   at ./ipl.pl line 42.
ok 12 - basi4a16-split-alpha-alpha.new and basi4a16-alpha.bin same
/home/ben/projects/image-png-libpng/t/libpng/basn6a16.png
not ok 13 - basn6a16-split-alpha-data.new and basn6a16-data.bin same
#   Failed test 'basn6a16-split-alpha-data.new and basn6a16-data.bin same'
#   at ./ipl.pl line 42.
ok 14 - basn6a16-split-alpha-alpha.new and basn6a16-alpha.bin same
/home/ben/projects/image-png-libpng/t/libpng/basi6a16.png
not ok 15 - basi6a16-split-alpha-data.new and basi6a16-data.bin same
#   Failed test 'basi6a16-split-alpha-data.new and basi6a16-data.bin same'
#   at ./ipl.pl line 42.
ok 16 - basi6a16-split-alpha-alpha.new and basi6a16-alpha.bin same
/usr/home/ben/oneoff/png-alpha/Achannel/screenshot-rgba.png
not ok 17 - screenshot-rgba-split-alpha-data.new and screenshot-rgba-data.bin same
#   Failed test 'screenshot-rgba-split-alpha-data.new and screenshot-rgba-data.bin same'
#   at ./ipl.pl line 42.
not ok 18 - screenshot-rgba-split-alpha-alpha.new and screenshot-rgba-alpha.bin same
#   Failed test 'screenshot-rgba-split-alpha-alpha.new and screenshot-rgba-alpha.bin same'
````
I'll try to get this done ASAP and post a fix, then let's see if that solves the problem.

**Comment by benkasminbullock** [comment]
My preliminary result is that there was an error in the original Achannel.pl causing an extra byte to be written for 16 bit channels. This error was replicated in the original "kungfu" which turned into "split_alpha", then the error was fixed in the new version of Image::PNG::Libpng. I am getting wrong lengths for the file for 16 bit images.

For the 08 36x36 images, I get:
````
-r--r--r--  1 ben  ben  1024 Apr 19  2020 basi4a08-alpha.bin
-r--r--r--  1 ben  ben  1024 Apr 19  2020 basi4a08-data.bin
-rw-r--r--  1 ben  ben  1024 Dec 21 10:00 basi4a08-split-alpha-alpha.new
-rw-r--r--  1 ben  ben  1024 Dec 21 10:00 basi4a08-split-alpha-data.new
````
The size for both is 1024 bytes as expected.

For the 16 bit 36x36 images I get, for example,

````
-r--r--r--  1 ben  ben  2048 Apr 19  2020 basi4a16-alpha.bin
-r--r--r--  1 ben  ben  2056 Apr 19  2020 basi4a16-data.bin
-rw-r--r--  1 ben  ben  2048 Dec 21 10:00 basi4a16-split-alpha-alpha.new
-rw-r--r--  1 ben  ben  2048 Dec 21 10:00 basi4a16-split-alpha-data.new
````
You can see that the length of the file `basi4a16-data.bin` is incorrect for a 36x36 image, whereas `basi4a16-alpha.bin` is OK, and this file agrees with my results.

Inspecting the files with `hexdump -C`, the basi4a16-data.bin file has bytes off by one.

So this seems to be an error in your file `Achannel.pl` which I had replicated in the original `split_alpha` code by accident, I went on to release the code to CPAN, and then when I rewrote the `split_alpha` code recently I corrected the error, hence the disagreement.

Can you confirm this?

**Comment by benkasminbullock** [comment]
I've added extended testing support here:

commit 3e7ef94f0bb97050a720f249520cda6adf29857c (HEAD -> master, origin/master)
Author: Ben Bullock <benkasminbullock@gmail.com>
Date:   Mon Dec 21 14:02:22 2020 +0900

    Extend split alpha tests

The split_alpha tests now extend to non-interlaced and interlaced, greyscale and RGB, and 8 and 16 bit depths.

**Comment by PhilterPaper** [comment]
That will take some digging around to confirm what you found and see if I need to fix something in the PDF::Builder code. I hope to get back to you later today at earliest.

**Comment by benkasminbullock** [comment]
I looked at your code again. To be on the safe side I unzipped it from the
source. I had a look at Achannel.pl. Running Achannel.pl again, I am not
even getting the same output as the -bin files:

-r--r--r--  1 ben  ben  2048 Apr 19  2020 basi4a16-alpha.bin
-rw-r--r--  1 ben  ben  2048 Dec 21 23:36 basi4a16-alpha.new

Data files are different here:

-r--r--r--  1 ben  ben  2056 Apr 19  2020 basi4a16-data.bin
-rw-r--r--  1 ben  ben  2048 Dec 21 23:36 basi4a16-data.new
-r--r--r--  1 ben  ben  2048 Apr 19  2020 basi6a16-alpha.bin
-rw-r--r--  1 ben  ben  2048 Dec 21 23:36 basi6a16-alpha.new

They are also different here:

-r--r--r--  1 ben  ben  6156 Apr 19  2020 basi6a16-data.bin
-rw-r--r--  1 ben  ben  6144 Dec 21 23:36 basi6a16-data.new

Here again:

-r--r--r--  1 ben  ben  2048 Apr 19  2020 basn4a16-alpha.bin
-rw-r--r--  1 ben  ben  2048 Dec 21 23:36 basn4a16-alpha.new
-r--r--r--  1 ben  ben  2056 Apr 19  2020 basn4a16-data.bin
-rw-r--r--  1 ben  ben  2048 Dec 21 23:36 basn4a16-data.new
-r--r--r--  1 ben  ben  2048 Apr 19  2020 basn6a16-alpha.bin
-rw-r--r--  1 ben  ben  2048 Dec 21 23:36 basn6a16-alpha.new

Again here:

-r--r--r--  1 ben  ben  6156 Apr 19  2020 basn6a16-data.bin
-rw-r--r--  1 ben  ben  6144 Dec 21 23:36 basn6a16-data.new

So there's no doubt that the .bin files are different from the .new files.
I checked it, and Achannel.pl looks like correct code to me so it looks as
if the fault is in whatever made the .bin files. Until you sent the bug
report I was using the .bin files for comparison, which are wrong, so my
code was agreeing with whatever you made .bin with. I don't have the code
which creates the .bin files, so the ball is in your court.

**Comment by PhilterPaper** [comment]
If I remember correctly, the ".bin" files were just created with the same code (Achannel.pl) as the ".new" files, with just the suffix changed. The ".bin" were intended to be read-only reference files, while you could play with the ".new" output.

Thinking it might be \n -> CRLF expansion (Windows), I added a couple `binmode $OUT;` statements when writing out the data and alpha files. This _did_ make a big difference in the alpha "screenshot" large file, and a small difference in two others. The data file is always 1x or 3x the alpha file, except for two cases where it's 8 bytes larger. Can you think of anything else in the Windows World that would add on a few extra bytes in a few cases? 

This is running with library 0.52. Upgrading to 0.54, I get the same size files and content. Ditto for 0.46. In only two cases do I get an oddball 'data' size: 16 bit grayscale both interlaced and non-interlaced end up with 8 extra bytes compared to the alpha channel. Since 'bin' is without binmode, we really can't compare against it any more. I'd still like to know what's going on with the two 16 bit gray files, but other than that, the sizes look OK.

I next have to figure out why the new library causes PDF::Builder to fall over dead, without giving a message. I'll try to work on that tonight.

**Comment by benkasminbullock** [comment]
Thanks for confirming. It is very unlikely to be related, but just in case, at the moment I have one "mystery" test result here on the right, for the Solaris operating system:

http://matrix.cpantesters.org/?dist=Image-PNG-Libpng+0.55

It is crashing on split_alpha with what looks like the 16-bit RGBA images.

But the Solaris C compiler is eccentric and has caused some problems in the past. Otherwise I don't have any problems with that code.

**Comment by PhilterPaper** [comment]
I installed the latest (0.54... it looks like 0.55 isn't _quite_ available from CPAN). It's definitely crashing and burning within split_alpha() -- so badly that Perl falls over dead and doesn't give me a message. 

I see in the POD that you've changed the interface to split_alpha() at some point. It used to be `$split = split_alpha($png);`, but now it's `$split = $png->split_alpha();`. I tried changing my code in PNG_IPL.pm to the new way, but it still died in split_alpha(). This is with a 17.28MB RGBA (32 bit). Under 0.47, it divided up into a 12.960MB data and a 4.320MB alpha, but now it's not even returning from split_alpha().

If you still have screenshot-rgba.png, that's the one it's choking on. At this point I can't see any more debugging that I can do on my end. Suggestions?

**Comment by benkasminbullock** [comment]
> I installed the latest (0.54... it looks like 0.55 isn't _quite_ available from CPAN). It's definitely crashing and burning within split_alpha() -- so badly that Perl falls over dead and doesn't give me a message.
> 

0.55 should be available, sometimes metacpan caches pages so you have to reload, anyway you can go to "Recent" to find newer versions.

https://metacpan.org/release/Image-PNG-Libpng

> I see in the POD that you've changed the interface to split_alpha() at some point. It used to be `$split = split_alpha($png);`, but now it's `$split = $png->split_alpha();`.

The documentation may have changed but the interface is the same, either `$png->split_alpha ()` (without the brackets if you prefer) or `split_alpha ($png)` will work.


> I tried changing my code in PNG_IPL.pm to the new way, but it still died in split_alpha(). This is with a 17.28MB RGBA (32 bit). Under 0.47, it divided up into a 12.960MB data and a 4.320MB alpha, but now it's not even returning from split_alpha().
> 
> If you still have screenshot-rgba.png, that's the one it's choking on. At this point I can't see any more debugging that I can do on my end. Suggestions?

Yes I have that file as part of Achannel.zip. I will try it out on my system and see if I can work out what might be going wrong. There is nothing that jumps to mind yet. If I can't work it out I might get you to run some tests for me. I don't use Perl on Windows so I'm not sure what Perl just stopping might mean.

**Comment by benkasminbullock** [comment]
OK, can you do this:

1. Download

https://cpan.metacpan.org/authors/id/B/BK/BKB/Image-PNG-Libpng-0.55_01.tar.gz

2. perl Makefile.PL;make;make test;make install

3. Try out your script again.

Thanks.

**Comment by PhilterPaper** [comment]
GNE! (Good News, Everyone!) I ran with 0.55_01 and it seems to be working properly now. It didn't fall over dead, and produced a good PDF with the expected images in typical run time: 
[124349.pdf](https://github.com/benkasminbullock/image-png-libpng/files/5730984/124349.pdf)

Whatever your latest changes were, they seem to have worked. Thank you for the fix. I'll update the PDF::Builder prereq to 0.56 when it's officially released. Unless you have anything else that requires continuing the discussion, feel free to close this ticket.

**Comment by benkasminbullock** [comment]
The new version is on CPAN now.
