### ISSUE TITLE
The images with a questionable license

### ISSUE THREAD

**Issue by ppisar** [benkasminbullock/image-png-libpng#36]
Image-PNG-Libpng-0.56 contains few images whose license is questionable for me:

Two images from XKCD:

* examples/life.png
* examples/life-gray.png

Their CC-BY-NC-2.5 license forbids a non-commercial use, requires quoting the author and a link to the license. The non-commercial restriction is not welcome in some software distributions, like Fedora. Could you please remove them? Or at least conform to the CC-BY-NC-2.5 by listing the author and the URL?

A lyrics of Bad City by Casey Rankin:

* t/qrpng.png

Despite that it's a QR code, it's a lyrics with a copyright. I think you should remove it.

An image of a man's face:

* t/tantei-san.png

It looks like a photo from an encyclopedia. Are you sure you have a permission to disseminate it?

Two icons:

* unt/chunks.png
* unt/logo_icon128.v101.png

Where are they from?

**Comment by benkasminbullock** [comment]
On Tue, 5 Jan 2021 at 00:25, Petr Pisar <notifications@github.com> wrote:

> Image-PNG-Libpng-0.56 contains few images whose license is questionable
> for me:
>
> Two images from XKCD:
>
>    - examples/life.png
>    - examples/life-gray.png
>
> Their CC-BY-NC-2.5 license forbids a non-commercial use, requires quoting
> the author and a link to the license.
>
 There is a link in the documentation.

> The non-commercial restriction is not welcome in some software
> distributions, like Fedora. Could you please remove them? Or at least
> conform to the CC-BY-NC-2.5 by listing the author and the URL?
>
These images do not form any part of the software itself, they are used in
the documentation and testing.


> A lyrics of Bad City by Casey Rankin:
>
>    - t/qrpng.png
>
> Despite that it's a QR code, it's a lyrics with a copyright. I think you
> should remove it.
>

Probably we should remove the entire Perl source code since it contains
similar quotes from copyrighted work The Lord of the Rings.

I can remove this tiny quote from the distribution if it is really a
problem for you, but again that image is not part of the software itself.


> An image of a man's face:
>
>    - t/tantei-san.png
>
> It looks like a photo from an encyclopedia. Are you sure you have a
> permission to disseminate it?
>
I don't have permission to disseminate it. It is a photograph of actor
Yusaku Matsuda from 1979. I could just use a random pixel image.


> Two icons:
>
>    - unt/chunks.png
>    - unt/logo_icon128.v101.png
>
> Where are they from?
>

Those are the Duckduckgo logo.

Those are part of an experiment, and should be only in the github
distribution, I'll remove them from the CPAN distribution.

**Comment by benkasminbullock** [comment]
I'd actually removed the qrpng.png image yesterday since the function it tests, any2gray8, is moving to another module Image::PNG::Util. The unt directory is removed from the CPAN distribution with the following commit:

a472677a52130bf6c89fdfea0fcc72f66343d78f

**Comment by benkasminbullock** [comment]
I've also changed qrpng.png in the Image::PNG::Util directory, in case you're thinking of distributing that with your Linux distribution.

https://raw.githubusercontent.com/benkasminbullock/image-png-util/ace88b49ea0d74d4414e39d41f128d23a02d136b/t/qrpng.png

That is a quote from Shakespeare who died 400 years ago, so it is out of copyright (there probably was no copyright law when he was alive anyway).

**Comment by ppisar** [comment]
On Mon, Jan 04, 2021 at 03:46:08PM -0800, Ben Bullock wrote:
> On Tue, 5 Jan 2021 at 00:25, Petr Pisar <notifications@github.com> wrote:
> > Image-PNG-Libpng-0.56 contains few images whose license is questionable
> > for me:
> >
> > Two images from XKCD:
> >
> >    - examples/life.png
> >    - examples/life-gray.png
> >
> > Their CC-BY-NC-2.5 license forbids a non-commercial use, requires quoting
> > the author and a link to the license.
> >
>  There is a link in the documentation.
>
I see. There is in lib/Image/PNG/Libpng.pod:

    L<Original image, licence statement and copyright notice
    here|https://xkcd.com/2391/>.

However, in my opinion, it is still missing a link to or a full copy of the
license text as requiered in 4a section of the license
<https://creativecommons.org/licenses/by-nc/2.5/legalcode>.

> > The non-commercial restriction is not welcome in some software
> > distributions, like Fedora. Could you please remove them? Or at least
> > conform to the CC-BY-NC-2.5 by listing the author and the URL?
> >
> These images do not form any part of the software itself, they are used in
> the documentation and testing.
>
Fodora does not make distinction between a code and a documention: Everything
what is distributed, must be usable for any (including commercial) purpose by
the user. Fedora also redistributes the source archive. If you keep the files
there, Fedora will have to keep stripping them from the archive before
redistributing. If you remove them, Fedora will have less work with packaging
your software.

> > A lyrics of Bad City by Casey Rankin:
> >
> >    - t/qrpng.png
> >
> > Despite that it's a QR code, it's a lyrics with a copyright. I think you
> > should remove it.
> >
> 
> Probably we should remove the entire Perl source code since it contains
> similar quotes from copyrighted work The Lord of the Rings.
> 
I'm not good at making a distinction between a fair-use short quotation and
the other uses. It's highly subjective.

**Comment by benkasminbullock** [comment]
> On Mon, Jan 04, 2021 at 03:46:08PM -0800, Ben Bullock wrote: On Tue, 5 Jan 2021 at 00:25, Petr Pisar ***@***.***> wrote: > Image-PNG-Libpng-0.56 contains few images whose license is questionable > for me: > > Two images from XKCD: > > - examples/life.png > - examples/life-gray.png > > Their CC-BY-NC-2.5 license forbids a non-commercial use, requires quoting > the author and a link to the license. > There is a link in the documentation.
> I see. There is in lib/Image/PNG/Libpng.pod: L<Original image, licence statement and copyright notice here|https://xkcd.com/2391/>. However, in my opinion, it is still missing a link to or a full copy of the license text as requiered in 4a section of the license <https://creativecommons.org/licenses/by-nc/2.5/legalcode>.

I'll add the link shortly.

> > The non-commercial restriction is not welcome in some software > distributions, like Fedora. Could you please remove them? Or at least > conform to the CC-BY-NC-2.5 by listing the author and the URL? > These images do not form any part of the software itself, they are used in the documentation and testing.
> Fodora does not make distinction between a code and a documention: Everything what is distributed, must be usable for any (including commercial) purpose by the user. Fedora also redistributes the source archive. If you keep the files there, Fedora will have to keep stripping them from the archive before redistributing. If you remove them, Fedora will have less work with packaging your software.

OK, I'll try to make things easy for you.

> > A lyrics of Bad City by Casey Rankin: > > - t/qrpng.png > > Despite that it's a QR code, it's a lyrics with a copyright. I think you > should remove it. > Probably we should remove the entire Perl source code since it contains similar quotes from copyrighted work The Lord of the Rings.
> I'm not good at making a distinction between a fair-use short quotation and the other uses. It's highly subjective.

It's gone now as noted.

**Comment by benkasminbullock** [comment]
Sorry, I hadn't got around to doing this yet. I will try to get rid of the bad images by the next release.

**Comment by benkasminbullock** [comment]
I've removed tantei-san.png and qrpng.png in this commit: 446a73a92e9f0f7651910eee420fc827d9d26609
